/**
 * Created by 94326 on 2019/01/07.
 */


export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERR = 'AUTH_ERR'
export const AUTH_SUCCESSTWO= 'AUTH_SUCCESSTWO'
export const AUTH_ERRTWO = 'AUTH_ERRTWO'
export const AUTH_SUCCESSTHREE= 'AUTH_SUCCESSTHREE'
export const AUTH_ERRTWOTHREE = 'AUTH_ERRTWOTHREE'
export const AUTH_SUCCESSFOUR= 'AUTH_SUCCESSFOUR'
export const AUTH_ERRTWOTFOUR = 'AUTH_ERRTWOTFOUR'